### ISSUE TITLE
HTML Tags not rendering correctly

### ISSUE THREAD

**Issue by PierreSenpai** [scott2000/answerset#1]
After updating anki to version 2.1.56 or higher, the html tags in the answer are annoyingly marked as errors. In the following screenshots you can see the same card with the exact same answer typed in:
1) version 2.1.55 Qt6
![image](https://github.com/scott2000/answerset/assets/99288816/5400164e-bce7-4ea6-a6cf-d1d869fba562)
2) version 2.1.56 Qt6
![image](https://github.com/scott2000/answerset/assets/99288816/0116cfef-ec4c-47b6-b20f-76fde529e2f1)
I noticed this problem when I updated my quite old anki installion (2.1.54 i think) to the newest version (2.1.65) and I would be pleased if you could revert this change to the pre .55 state or fix the problem.
Thank you in advance!

Edit: Now I noticed that the README.md for version .60 states that html tags are rendered this way but I'm still wondering why this is the case suddenly since version .56

**Comment by scott2000** [comment]
I don't think I made any changes to the add-on that would cause this to happen, so it must've been a change to Anki that caused it. I'll look into it and see if I can find a fix.

Would it be possible to see the card and the template you're using so I can try to reproduce the issue?

**Comment by scott2000** [comment]
Thanks! I'll see if I can figure out what's going wrong.

**Comment by scott2000** [comment]
I think I fixed the issue. It should follow the normal Anki behavior now, which is to strip any HTML from the expected answer before checking it against the given answer.
