### ISSUE TITLE
Another bug with interaction between features, I think

### ISSUE THREAD

**Issue by DianeNox** [scott2000/answerset#13]
Hello again :D Really happy with the updates by the way, as I hope the *lack* of any opened issues made clear! I did find one more, unfortunately xD

It's kind of similar to the previous bug report, now that I think about it. Though, this time it's the interaction between x/y and brackets, I assume at least.

<img width="742" alt="Screenshot 2023-12-23 121520" src="https://github.com/scott2000/answerset/assets/51899303/0314c9ef-40bf-42d9-b579-98fc2ab925f5">

Just in case that isn't completely clear from the screenshot: the intended accepted answers are "tar en mastergrad", "tar en bachelorgrad", AND "tar en grad". I might just bypass the issue by changing the card to x/y/z format, but I still wanted to report it.

**Comment by scott2000** [comment]
I'm glad to hear that they've been helpful! :)

But hmm yeah I think I know what's going on. I think it's ignoring the brackets in this case, so it sees it as `master/bachelorgrad`, so it's expecting just `master` or `bachelorgrad` but not `mastergrad`. I think I know how to fix it, so I should have an update for it in the next couple days!

**Comment by scott2000** [comment]
I updated it so now it should work the way you were expecting. Let me know if you find anything else!
