### ISSUE TITLE
Easier Alternatives - Feature Suggestion

### ISSUE THREAD

**Issue by DianeNox** [scott2000/answerset#23]
Hello once again! :D I'm incredibly happy with the newest update, it fixed absolutely everything. I felt a little adrift, honestly. No bugs for me to report D:

Anyways! I've come to notice something I'd like, and it's partially inspired by what @Isslea mentioned in #2: Multiple-word alternatives. There's a few use-cases on my mind, though they're all related.

The most common one is rather simple: Sometimes my cards say "I'm", and sometimes they say "I am". When I want the card to allow both, I usually do this:

`"I'm happy., I am happy."`

Another method I use for alternatives is a mixture of slashes and brackets which works beatifully nowadays:

`"I went to the cinema/movie (theater)."`

Now, both of those *work*. They're just. It could be better.

-------------

So much for the situation, now for the actual feature suggestion. Particularly for reasonably common cases like "I'm/I am", I wonder if you might be able to do another setting so that I can specify in the config particular strings of characters which should be treated as identical. I imagine the setting to look something like this:

```txt
{
    ...
    "Identical Strings":
        ["I'm", "I am"],
        ["xy", "xz"]
}
```

The specific case of I'm vs. I am feels so ridiculously common that I am really hoping for this one to be implemented. Hell, if the feature works out as I hope it will, then you could also specify that " not" (mind the extra space) can also be "n't". or [" is", "'s"], [" are", "'re"], and so on. The same for similar features in other languages.

------------

I had half an essay typed up here but then decided to scrap it and instead just give the summary: You *already* implemented multiple-word alternatives, probably by sheer accident, see my movie theater example above. My feature suggestion, too, aims to make them easier on the user - basically, to save me from having to type a whole bucketload of brackets. If you ever were to do more work on that topic, on multiple-word alternatives, I would hope that focus remains: that the new feature will make the plugin easier on the user, to make the plugin work with the user's cards, instead of the user having to adjust their cards for the plugin.

To think that the issue is still this long after I approximately halved it. Umm. Whoops? But, oh well. If nothing else, I hope that shows how much I'd appreciate this. ...And how tired I am of ***brackets***!

Right. Thanks a lot for all the hard work you do! Looking forward to hearing what you think about this!

**Comment by scott2000** [comment]
I'm glad to hear it's been working out! :)

I think after making that previous  change, your idea should be pretty easy to do, and it seems like it would be pretty useful. Let me think about it for a bit and figure out the best way to do it! I think I should be able to make it so that you can configure a list of strings which would be treated as being effectively the same like you suggested.

**Comment by scott2000** [comment]
Ok, I added it under a config option called "Equivalent Strings"! This is what your example config would look like:

```
{
    ...
    "Equivalent Strings": [
        ["I'm", "I am"],
        ["xy", "xz"]
    ],
    ...
}
```

Also for alternatives containing spaces, `I went to the [cinema/movie theater]` is also supported (as suggested in #2). However, the text inside the brackets is still considered optional, so this might not be ideal. I might add another config option in the future to support this better.

Please let me know if you see any issues!
