### ISSUE TITLE
Approximate numeric comparison

### ISSUE THREAD

**Issue by aleksejrs** [scott2000/answerset#27]
I used to use https://github.com/ospalh/anki-addons/blob/develop/scalar.py, but I modified it to use different pass factors for different values. Anki stopped being compatible with it. Your add-on seems like the place for the feature.

**Comment by scott2000** [comment]
That seems like it should be possible to add. Let me look into it.

**Comment by scott2000** [comment]
I added a config option for approximate numeric comparisons. You can find the documentation [here](https://github.com/scott2000/answerset/blob/main/doc/numeric_comparison.md). Please let me know if there's any issues!

**Comment by aleksejrs** [comment]
I think it should be specific to decks, note types, or tags. I was using Scalar.py for age, so it was 1.5 for 1-15, 3 for 15-21, 5 for 21-60, 7 for 60-75, 10 for 75-90, 12 for >90. This precision with photos is probably impossible, but the variability applies only to those cards. Of course, when I get around to adding it to my copy, I will probably find a way to make it depend on the note type.

**Comment by scott2000** [comment]
I'm not too familiar with how Anki works apart from how I use it personally, so I'm not completely sure how that would work, or how it would integrate with the existing configuration options.
