### ISSUE TITLE
the monkey patch is broken by Anki 24.10 Beta 2

### ISSUE THREAD

**Issue by aleksejrs** [scott2000/answerset#39]
https://github.com/ankitects/anki/pull/3464

**Comment by scott2000** [comment]
Thanks, I'll look into it! This is one of the dangers of implementing it this way I suppose.

**Comment by scott2000** [comment]
I created [a forum post](https://forums.ankiweb.net/t/hook-for-collection-compare-answer/50278) with a feature request to add a hook, since I didn't see any existing hook that would work for this.
