### ISSUE TITLE
Possible Bug with "x/y."

### ISSUE THREAD

**Issue by DianeNox** [scott2000/answerset#5]
Ello... I really don't know how to explain this one, so here's the screenshot.
<img width="709" alt="Screenshot 2023-11-28 081442" src="https://github.com/scott2000/answerset/assets/51899303/04e4f79a-517c-46e1-bed6-6aadff228e0a">

I would have expected this to parse without an error shown, with Yen as the chosen option between that and Ya, and the . as an ignored character so also skipped. On other cards, the dots being ignored and the options parsing as correct with the other simply greyed out, worked just fine. So I assume there's some issue with the combination between the two features, or it being at the end of the text?

**Comment by scott2000** [comment]
I released an update with a fix! Please try it and let me know if you see any other issues.
